### ISSUE TITLE
Thread-safety

### ISSUE THREAD

**Issue by ValdikSS** [x64dbg/x64dbgpy#8] opened 2016-09-07 14:39 UTC
If I call `x64dbgpy.pluginsdk.debug.Run()` from breakpoint callback, x64dbg debug thread hangs (the UI still works). Is there a proper way to do that?

**Comment by mrexodia** [comment] 2016-09-07 17:08
You cannot do that, not even from inside x64dbg. You have to create a new
thread and handle it from there.

**Comment by techbliss** [comment] 2016-09-08 07:17
yes this behavior is weird, must be a callback issue that makes x64dbgpy slow in responde.

test with notepad.exe

set break point in start of thread,restart debugger it break on BP then in GUI press run, it continue and GUI is accesseble and notepad continue.

restart again it break on BP, using python.

```
import x64dbgpy
x64dbgpy.pluginsdk.debug.Run()
```

GUI hangs a little before doing the job.i imaging on larger programs it will fail completely.

However if used 

```
x64dbgpy.pluginsdk.debug.Stepin()
```

GUI responds instantly so could be only the call back for run is somehow of.

**Comment by techbliss** [comment] 2016-09-08 10:13
this may work if added to the callback for run(), c++ debugger must have something simular i guess, since its still responsive after run in GUI.

[QThread](https://nikolak.com/pyqt-threading-tutorial/)

Another option 

Test via python command line in GUi dont make GUI freeze, only via execute script

https://github.com/x64dbg/x64dbgpy/blob/v25/py.cpp#L127

```
Python "x64dbgpy.pluginsdk.debug.Run()"
```

![thread](https://cloud.githubusercontent.com/assets/3592375/18345852/96bfecd8-75bd-11e6-99af-049e402c6f5f.png)

**Comment by mrexodia** [comment] 2016-09-08 10:26
The reason for this is as follows:

To effectively halt the process, x64dbg receives debug events. The debug engine will have callbacks for breakpoints and not call `ContinueDebugEvent` before these return. Inside this callback (breakpoint handler code) this happens:

``` c++
//set the GUI lock (unlocked when user presses run button)
lock(WAITID_RUN);

//plugin handle code: calls python breakpoint callback **synchronously** (wait for callback to return)
PLUG_CB_BREAKPOINT bpInfo;
BRIDGEBP bridgebp;
memset(&bridgebp, 0, sizeof(bridgebp));
bpInfo.breakpoint = &bridgebp;
BpToBridge(&bp, &bridgebp);
plugincbcall(CB_BREAKPOINT, &bpInfo);

//some extra code for handling breakpoint (not important)

//wait until the user resumes (until unlock(WAITIT_RUN) is called)
wait(WAITID_RUN);
```

Now, the code that will be called when you use `x64dbgpy.pluginsdk.debug.Run()`:

``` c++
SCRIPT_EXPORT void Script::Debug::Run()
{
    DbgCmdExecDirect("run");
    while(DbgIsDebugging() && dbgisrunning())  //wait until the debugger paused
        Sleep(1);
}
```

What will happen is that the breakpoint callback does not return until the debugger is paused again, so it will deadlock and never return.

To mitigate this problem, x64dbg uses multiple threads. The breakpoint callback itself (eg the breakpoint handler code) uses `wait(WAITID_RUN)`, which hands over control to other threads (GUI thread), this way the user can interact with the GUI. When the user presses the run button (eg executes the `run` command) the code for `wait(WAITID_RUN)` will return and the debug loop continues.

If you want to use the `x64dbgpy.pluginsdk.debug` functions you have to use them directly from your python code (I don't know python so forgive my shitty code):

``` python
debug.SetBreakpoint(addr) # returns immediately
while register.GetCIP() != addr:
    debug.Run()
debug.Step() # whatever you want to do at that breakpoint
```

**Comment by ValdikSS** [comment] 2016-09-08 10:31
So either we should write an endless loop which would check EIP/RIP on an iteration or hack up threads for callbacks, am I right? The latter sounds better for me, I'll try it, thanks.

**Comment by mrexodia** [comment] 2016-09-08 10:33
Well, this should be integrated in the Python layer of x64dbgpy so users don't have to worry about this and can use breakpoint callbacks as they expect. Basically you are now writing scripts similar to ODBGScript where you just simulate user interaction and have a sequence of events that wait for the debugger to break again.

**Comment by ValdikSS** [comment] 2016-09-09 13:09
Well, I'm not sure if I did what you meant but either new thread with `run()` or endless loop won't work. Any ideas?

**Comment by techbliss** [comment] 2016-09-09 14:26
Using the same callback and have two different outcome is also very wierd.

We agree these two callbacks are the same.

from cmd in x64dbg
    Python "x64dbgpy.pluginsdk.debug.Run()"  
= no halt

```
import x64dbgpy
x64dbgpy.pluginsdk.debug.Run()
```

= halt

I could fix it in the editor but i agree with @mrexodia  that it should be fixed in x64dbg top layer.

@realgam3 maybe the dev got a way of fixing this.

**Comment by mrexodia** [comment] 2016-09-09 14:37
This code works fine, but I don't know about python I will try... https://github.com/x64dbg/Scripts/blob/master/UpxUnpacker.cpp

**Comment by ValdikSS** [comment] 2016-09-09 14:53
Hrm, I think it's all about `AsyncStart()`. Is there a way to use it in Python?

**Comment by mrexodia** [comment] 2016-09-09 14:54
```
from x64dbgpy.pluginsdk import *
import sys

cip = register.GetCIP()
if memory.ReadByte(cip) != 0x60:
    gui.Message("Start at UPX entry point (1:[CIP]==0x60)")
    exit(0)

x64dbg.DbgCmdExecDirect("bc")
x64dbg.DbgCmdExecDirect("bphwc")
found = pattern.FindMem(cip, 0x1000, "83 EC ?? E9");
if found == 0:
    gui.Message("Could not find pattern!");
    exit(0)

debug.SetBreakpoint(found + 3)
debug.Run()
debug.StepIn()

cip = register.GetCIP()
comment.Set(cip, "OEP Found by Python!")
gui.Message("Reached OEP. Use Scylla to dump and restore imports!")
x64dbg.DbgCmdExec("scylla")
```

Create a file called `boobs.py`, use `Plugins -> x64dbgpy -> Open Script...` and it will unpack UPX.

**Comment by ValdikSS** [comment] 2016-09-09 15:00
Well, I'm trying to make a script which would save data from the registers and write it to a file. I need to be able to interact with the GUI while the script is active. Right now it works perfectly using breakpoint callback without resuming execution from the script, so I need to hold F9 for the program to continue after breakpoint.

If I use a code from UPX unpacker, the GUI thread would hang while the script is executing and I would not be able to interact with the x64dbg, but the script probably would work.

**Comment by mrexodia** [comment] 2016-09-09 15:04
Yeah, it's pretty easy to do, but it requires x64dbgpy to not start the script on the GUI thread. Let me try something.

**Comment by mrexodia** [comment] 2016-09-09 15:19
@ValdikSS try https://github.com/x64dbg/x64dbgpy/releases/tag/c4f05f43

**Comment by mrexodia** [comment] 2016-09-09 15:20
Open Async

**Comment by techbliss** [comment] 2016-09-09 15:25
for now you can you hack via command line

```
import x64dbgpy
from x64dbgpy.pluginsdk.x64dbg import *
DbgCmdExec("Python x64dbgpy.pluginsdk.debug.Run()")
```

GUI wont hang :dancers:

**Comment by ValdikSS** [comment] 2016-09-09 15:35
@mrexodia https://github.com/x64dbg/x64dbgpy/releases/tag/c4f05f43 won't import first time correctly, that's why input and output are not hooked and you can't see what's going on. It could be I did something wrong. I'll try @techbliss workaround.

**Comment by mrexodia** [comment] 2016-09-09 15:41
donnow, you can try the PythonDebug command

**Comment by ValdikSS** [comment] 2016-09-09 15:47
@techbliss, your workaround introduces race condition. It works for some seconds but then x64dbg completely crashes.

**Comment by mrexodia** [comment] 2016-09-09 15:49
What is the problem exactly with the new release?

**Comment by ValdikSS** [comment] 2016-09-09 15:50
Just for you to understand, I have the code like this

``` python
import x64dbgpy.pluginsdk as sdk

def bpc():
    print "Got BP!"
    sdk.x64dbg.DbgCmdExec('Python sdk.debug.Run()')

```

And I manually set the breakpoint callback using the following command:

```
Breakpoint.add(Register.EIP, bpc)
```

**Comment by mrexodia** [comment] 2016-09-09 15:55
so all you want to do is resume from the breakpoint?

Just use `sdk.x64dbg.DbgCmdExecDirect("run")` the `debug.*` commands will _wait_ and thus deadlock.

**Comment by ValdikSS** [comment] 2016-09-09 15:57
@mrexodia 

> What is the problem exactly with the new release?

```
[PLUGIN] command "PythonDebug" registered!
[PYTHON] Found valid PythonHome in the plugin settings!
[PYTHON] PythonHome: "C:\Python27\"
C:\Users\vboxdbg\Downloads\x64dbg\release\x32\plugins\x64dbgpy
[PYTHON] Could not import x64dbgpy.
[PLUGIN] x64dbgpy v1 Loaded!
```

And there's no output in the log. I had the same issue then I copied Python module to the `x32\plugins\x64dbgpy` and not to `C:\Python27\Lib/site-packages`. 37d3f5bb works fine from `site-packages` and not from `plugins`, c4f05f43 doesn't work from both folders.

Am I missing something?

**Comment by ValdikSS** [comment] 2016-09-09 16:01
> so all you want to do is resume from the breakpoint?

No, that's just the small test script which shows the issue. I need to beak on breakpoint, read some values from memory, save it to the file and continue execution from the script. Yet I need to interact with the x64dbg while the script is running. By interacting I mean to be able to add breakpoint, switch tabs, etc.

**Comment by techbliss** [comment] 2016-09-09 16:24
@mrexodia new release just make x64dbg quit when running command 

```
 import x64dbgpy
 x64dbgpy.pluginsdk.debug.Run()
```

better rool back changes

**Comment by mrexodia** [comment] 2016-09-09 16:26
I just tried:

```
from x64dbgpy.pluginsdk import *
import sys

def breakpointCallback():
    print "EAX: 0x%x" % Register.EAX
    x64dbg.DbgCmdExecDirect("run")

Breakpoint.add(Register.EIP, breakpointCallback)
x64dbg.DbgCmdExec("run")
```

**Comment by mrexodia** [comment] 2016-09-09 17:02
https://ci.appveyor.com/project/mrexodia/x64dbg-python/build/artifacts

**Comment by mrexodia** [comment] 2016-09-09 17:04
also @ValdikSS please join http://telegram.x64dbg.com or http://gitter.x64dbg.com or http://irc.x64dbg.com

**Comment by techbliss** [comment] 2016-11-15 12:48
try new version editor.
[v2.0](https://github.com/techbliss/X64dbg_script_editor)
GUI should not hang when in the new version while running debugger.

**Comment by techbliss** [comment] 2016-12-17 18:42
This can be closed now.

**Comment by mrexodia** [comment] 2016-12-17 18:43
I don't think so, the actual issue wasn't really fixed...

**Comment by techbliss** [comment] 2016-12-17 18:50
yes it is 
```
x64dbgpy.pluginsdk.debug.Run() 

```
wont hang UI anumore

**Comment by mrexodia** [comment] 2016-12-17 20:38
That is true but that was because of a work around done in x64dbg. The
script will still infinitely run if you do this.

**Comment by techbliss** [comment] 2016-12-17 20:54
But GUI won not hang, and that was the issue?

Also not sure what fixes that where made, but before i made some changes to the editor there where still hanging.However none now.

https://www.youtube.com/watch?v=iDIHPZotjIY&feature=youtu.be

**Comment by mrexodia** [comment] 2016-12-20 15:30
It's up to @ValdikSS to close this.

**Comment by JeremyWildsmith** [comment] 2018-03-15 08:02
Feb 14 2018 still has this hanging issue.

**Comment by mrexodia** [comment] 2018-03-15 08:04
@JeremyWildsmith It's not a bug, you are using x64dbgpy wrong

**Comment by JeremyWildsmith** [comment] 2018-03-15 08:09
@mrexodia 
I disagree; why is it even possible to create a deadlock condition in the GUI thread from within a python script? Also, the way that people resume the debugging via the script is literally the first thing _everyone_ will try, so probably not a good idea to mark as not-fix. But I can stick with this "workaround."

Thanks

**Comment by mrexodia** [comment] 2018-03-15 08:15
Unfortunately I cannot solve the halting problem. If you have a solution to this problem, let me know.

You can find more information about how x64dbg works here: https://x64dbg.com/blog/2016/10/20/threading-model.html

**Closed as completed by mrexodia** 2018-03-15 08:15 UTC
